name: Deploy to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TATUM_API_KEY: ${{ secrets.TATUM_API_KEY }}
  POLYGON_NETWORK: mainnet
  NODE_ENV: production

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Validate Tatum Configuration
        run: |
          curl -X GET "https://api.tatum.io/v3/polygon/info" \
          -H "x-api-key: ${{ secrets.TATUM_API_KEY }}" \
          -H "Content-Type: application/json"

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Create Sentry Release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production

      - name: Monitor Deployment
        run: |
          curl -X POST "https://api.tatum.io/v3/monitoring" \
          -H "x-api-key: ${{ secrets.TATUM_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "type": "ADDRESS_MONITORING",
            "address": "${{ secrets.CONTRACT_ADDRESS }}",
            "chain": "MATIC",
            "url": "${{ secrets.WEBHOOK_URL }}"
          }'

      - name: Discord Notification
        if: always()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          description: Deployment to Vercel
          details: ${{ github.event.head_commit.message }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
